spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1521/batch
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      check_nullablity: true
    show-sql: true


logging.level:
  org.hibernate:
    type: trace
    SQL: debug
